package com.dawei.entity;

/**
 * A股推送策略分类
 */
public enum AStockPushType {
    SILENT,
    REPORT_ONLY,
    REALTIME_OPPORTUNITY,
    REALTIME_RISK,
    REALTIME_HEALTH_ALERT,
    MACRO_REALTIME_OPPORTUNITY,
    MACRO_REALTIME_RISK,
    MARKET_PULSE_OPPORTUNITY,
    MARKET_PULSE_RISK,
    POST_CLOSE_RISK_DIGEST
}
